version: "3.8"

services:
  database:
    container_name: database
    image: postgres:13.8
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - "5432:5432"
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: TechnicalChallengeBackEnd
    ports:
      - 6578:8800
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
      - ASPNETCORE_URLS=http://+:8800
    depends_on:
      - database
